version: '3.8'
services:
  db:
    image: postgres:15
    container_name: ppc_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ppcuser
      POSTGRES_PASSWORD: ppcpass
      POSTGRES_DB: ppc_research
    volumes:
      - ppc_pgdata:/var/lib/postgresql/data

volumes:
  ppc_pgdata:
